# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10BeIpWUCHrcTP4B5d74YFRWtKXGxjOme
"""

from flask import Flask,render_template,flash, request, url_for
!pip install google-cloud-automl
from google.cloud import automl
from google.api_core.client_options import ClientOptions
import os
from google.colab import drive

drive.mount('/content/gdrive', force_remount= True)
path = "gdrive/My Drive/Colab Notebooks/BSA/classificationproject-349308-8e6bee0ea720.json"

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = path
app = Flask(__name__)
@app.route("/")
def hello():
    return render_template('index.HTML')

@app.route('/result',methods = ['POST', 'GET'])
def result():
    if request.method == 'POST':
        text = request.form.get("targetfrase")
        project_id = "classificationproject-349308"
        model_id = "TCN979071124069416960"
        content = text
        options = ClientOptions(api_endpoint='eu-automl.googleapis.com')
        prediction_client = automl.PredictionServiceClient.from_service_account_json("classificationproject-349308-8e6bee0ea720.json", client_options=options)
        model_full_id = automl.AutoMlClient.model_path(project_id,'eu',model_id)
        text_snippet = automl.TextSnippet(content=content,mime_type='text/')
        payload = automl.ExamplePayload(text_snippet=text_snippet)
        response = prediction_client.predict(name=model_full_id, payload=payload)
        return render_template("result.HTML", data=response.payload, result=text)
    if request.method == 'GET':
        return "<h3> nothing to show </h3>"
if __name__ == '__main__':

    app.run(port=int(os.environ.get("PORT",8080)),host='0.0.0.0',debug=True)



